#define rom
#define ram
#define code
#define near
#define far
#define interrupt
#define __interrupt
#define persistent
#define bank0
#define bank1
#define bank2
#define bank3
#define eeprom
#define low_priority
#define high_priority
#define inline
#define compiled
#define nonreentrant
#define software
#define reentrant
#define __compiled
#define __nonreentrant
#define __software
#define __reentrant
#define fiq
#define irq
#define __no_init
#define __inline
#define __bit
#define __asm
#define __CONFIG(x)
#define __PROG_CONFIG(x)
#define __attribute__(x)
#define __interrupt(x)

/* CCI Keywords */
#define __at(x)
#define __section(x)
#define __bank(x)
#define __align(x)
#define __interrupt(x)
#define asm(x)
#define __far
#define __near
#define __persistent
#define __xdata
#define __ydata
#define __eeprom
#define __pack
#define __deprecate